"""Automated Local Exploitation for Difference Imaging Analysis (DIA)

This script implements the 'Local Exploitation' phase of the Hybrid Global-Local 
Optimization strategy. Following the global exploration phase, 
this script fine-tunes the continuous Gaussian parameters (sigmas) using the 
derivative-free Powell optimization method, holding the discrete degrees constant.

Prerequisites & Environment Setup:
    1. ISIS Installation: The base ISIS tools must be compiled and accessible. 
       This script expects to run relative to the register macro directory 
       (e.g., ../../isis/register/).
    2. Data Preparation: Target FITS images must be in a dedicated directory. 
       A reference image explicitly named 'ref.fits' MUST be present.
    3. Configuration: Update the 'IM_DIR' variable in your ISIS 'process_config' 
       file to point to the target image directory.

Usage:
    python optimize_isis_local.py

    Note: Before executing, manually update the `initial_sigmas` variable in the 
    __main__ block with the best sigma values discovered during the global 
    exploration phase.
"""

import re
import subprocess
from io import StringIO

import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import minimize

# Global variables to track loss history efficiently without double-evaluating
loss_history = []
_last_evaluated_loss = None


def loss_fc(array):
    """Calculates the loss function for difference imaging evaluation.

    Args:
        array (np.ndarray): A 2D numpy array where the first column represents 
            the difference array (d_arr) and the second column represents 
            the scaling array (s_arr).

    Returns:
        float: The computed loss value averaged over the number of images.
    """
    no_images = 12
    d_arr = array[:, 0]
    s_arr = array[:, 1]
    
    return np.sum(d_arr**2 + (s_arr / 5)**2) / no_images


def update_sigmas(config_path, sigmas):
    """Updates the ISIS configuration file with new continuous sigma values.

    Iterates through the configuration file and dynamically replaces only the 
    sigma parameters for each Gaussian component, leaving the degrees untouched.

    Args:
        config_path (str): The file path to the ISIS configuration file.
        sigmas (np.ndarray): Array of float sigma values to be injected.
    """
    with open(config_path, 'r') as f:
        lines = f.readlines()

    def replace_line(pattern, new_value, lines_list):
        new_lines = []
        for line in lines_list:
            if re.match(rf"^{pattern}\b", line):
                parts = line.split()
                if len(parts) > 1:
                    parts[1] = str(new_value)
                    line = ' '.join(parts) + '\n'
            new_lines.append(line)
        return new_lines

    for i, sigma in enumerate(sigmas, start=1):
        lines = replace_line(f"sigma_gauss{i}", sigma, lines)

    with open(config_path, 'w') as f:
        f.writelines(lines)


def pipeline_loss(sigmas):
    """Objective function for the Powell optimization algorithm.

    Updates the configuration, triggers the external ISIS C-shell script, 
    parses the standard output, and evaluates the loss.

    Args:
        sigmas (np.ndarray): 1D array containing the sigma parameters 
            generated by the optimizer.

    Returns:
        float: The calculated loss for the current parameter set. Returns a 
            high penalty value (1e6) if the subprocess fails.
    """
    global _last_evaluated_loss
    
    config_path = r'../../isis/register/default_config'
    update_sigmas(config_path, sigmas)
    
    result = subprocess.run(
        ['csh', 'subtract_copy.csh'],
        cwd='../../isis/register',
        capture_output=True,
        text=True
    )

    if result.returncode != 0 or not result.stdout.strip():
        print("Run failed or empty output; penalizing loss.")
        print("STDERR:", result.stderr)
        _last_evaluated_loss = 1e6
        return _last_evaluated_loss

    try:
        data = np.loadtxt(StringIO(result.stdout), delimiter=',')
    except Exception as e:
        print(f"Error parsing output: {e}")
        _last_evaluated_loss = 1e6
        return _last_evaluated_loss

    loss = loss_fc(data)
    _last_evaluated_loss = loss
    
    print(f"Evaluated: Sigmas={sigmas}, Loss={loss:.6f}")
    return loss


def callback_tracker(sigmas):
    """Records parameters and loss at each iteration step.
    
    Utilizes the cached loss from the most recent pipeline_loss evaluation 
    to avoid re-running the computationally expensive C-shell script.

    Args:
        sigmas (np.ndarray): The current best sigma parameters at this iteration.
    """
    global _last_evaluated_loss
    loss_history.append((sigmas.copy(), _last_evaluated_loss))
    print(f"\n[Iteration Complete] Best sigmas={sigmas}, loss={_last_evaluated_loss:.6f}\n")


if __name__ == "__main__":
    # --- Optimization Setup ---
    # These should ideally be the best sigmas found from the Global Exploration script
    initial_sigmas = np.array([0.99102455, 5.69203562, 1.43097584])

    # Dynamically define bounds: +/- 2 from initial values, clipped at 0.5 and 10.0
    bounds = [
        (max(0.5, initial_sigmas[0] - 2), min(10.0, initial_sigmas[0] + 2)),
        (max(0.5, initial_sigmas[1] - 2), min(10.0, initial_sigmas[1] + 2)),
        (max(0.5, initial_sigmas[2] - 2), min(10.0, initial_sigmas[2] + 2))
    ]

    # Powell method specific options to scale the initial step sizes
    scale = 0.05
    direc = np.eye(len(initial_sigmas)) * scale

    print("Starting Local Exploitation (Powell method)...")
    
    # --- Execute Optimization ---
    result = minimize(
        pipeline_loss,
        initial_sigmas,
        method='Powell',
        bounds=bounds,
        callback=callback_tracker,
        options={'direc': direc, 'disp': True, 'maxiter': 20}
    )

    # --- Results & Visualization ---
    print("\n==============================")
    print("Optimization Complete!")
    print(f"Best sigmas : {result.x}")
    print(f"Minimum loss: {result.fun:.6f}")
    print("==============================\n")

    print("Loss convergence history:")
    for i, (s, l) in enumerate(loss_history):
        print(f" Iteration {i+1:02d}: sigmas={s}, loss={l:.6f}")

    # Plot the convergence history
    plt.figure(figsize=(8, 5))
    plt.plot([l for _, l in loss_history], marker='o', linestyle='-', color='b')
    plt.title("Local Exploitation: Loss Convergence")
    plt.xlabel("Iteration")
    plt.ylabel("Loss Function Value")
    plt.grid(True)
    plt.tight_layout()
    plt.show()