"""Automated Hybrid Optimization for Legacy Difference Imaging Analysis (DIA)

This script implements a Hybrid Global-Local Optimization strategy to tune 
Gaussian parameters for the legacy ISIS C-shell macros. 

Design Choice:
    The pipeline is designed to decouple 'Global Exploration' and 'Local Exploitation'. 
    Due to the high computational cost of ISIS image processing, 'no_local_search=True' 
    is enabled in the Dual Annealing algorithm. This allows the script to efficiently 
    identify the most promising global minima (valleys) without the overhead of 
    frequent local refinements. A separate local search stage is intended to follow 
    this process to fine-tune the discovered parameters.

Prerequisites & Environment Setup:
    1. ISIS Installation: The base ISIS tools must be compiled and accessible. 
       This script expects to run relative to the register macro directory 
       (e.g., ../../isis/register/).
    2. Data Preparation: Target FITS images must be in a dedicated directory. 
       A reference image explicitly named 'ref.fits' MUST be present in this directory.
    3. Configuration: Update the 'IM_DIR' variable in your ISIS 'process_config' 
       file to point to the target image directory created in Step 2.

Usage:
    python optimize_isis_global.py

    Note: Optimization can be safely interrupted at any time using Ctrl+C. 
    The script handles KeyboardInterrupt and will output the best 
    parameters discovered up to that point.
"""

import subprocess
from io import StringIO

import numpy as np
from scipy.optimize import dual_annealing

# Global variables to track the best parameters during optimization
best_loss = np.inf
best_params = None


def loss_fc(array):
    """Calculates the loss function for difference imaging evaluation.

    Args:
        array (np.ndarray): A 2D numpy array where the first column represents 
            the difference array (d_arr) and the second column represents 
            the scaling array (s_arr).

    Returns:
        float: The computed loss value averaged over the number of images.
    """
    no_images = 12
    d_arr = array[:, 0]
    s_arr = array[:, 1]
    
    return np.sum(d_arr**2 + (s_arr / 5) ** 2) / no_images


def update_config(config_path, deg_values, sigma_values):
    """Updates the ISIS configuration file with new degree and sigma values.

    Iterates through the configuration file and dynamically replaces the 
    target parameters for each Gaussian component.

    Args:
        config_path (str): The file path to the ISIS configuration file.
        deg_values (np.ndarray): Array of integer degree values.
        sigma_values (np.ndarray): Array of float sigma values.
    """
    with open(config_path, "r") as f:
        lines = f.readlines()

    def replace_line(line, pattern, new_value):
        if line.strip().startswith(pattern):
            parts = line.split()
            if len(parts) > 1:
                parts[1] = str(new_value)
                return " ".join(parts) + "\n"
        return line

    for i, (deg, sigma) in enumerate(zip(deg_values, sigma_values), start=1):
        lines = [replace_line(line, f"deg_gauss{i}", int(deg)) for line in lines]
        lines = [replace_line(line, f"sigma_gauss{i}", sigma) for line in lines]

    with open(config_path, "w") as f:
        f.writelines(lines)


def pipeline_loss(x, config_path, n):
    """Objective function for the dual annealing optimization algorithm.

    Updates the configuration, triggers the external ISIS C-shell script, 
    parses the standard output, and evaluates the loss.

    Args:
        x (np.ndarray): 1D array containing the concatenated degree and sigma 
            parameters generated by the optimizer.
        config_path (str): The file path to the ISIS configuration file.
        n (int): The number of Gaussian components being optimized.

    Returns:
        float: The calculated loss for the current parameter set. Returns a 
            high penalty value (1e6) if the subprocess fails or outputs incorrectly.
    """
    global best_loss, best_params

    deg_values = np.round(x[:n]).astype(int)
    sigma_values = np.clip(x[n:], 0.5, 10.0)

    update_config(config_path, deg_values, sigma_values)

    result = subprocess.run(
        ["csh", "subtract_copy.csh"],
        cwd="../../isis/register",
        capture_output=True,
        text=True
    )

    if result.returncode != 0 or not result.stdout.strip():
        print("Run failed or empty output.")
        return 1e6

    try:
        data = np.loadtxt(StringIO(result.stdout), delimiter=",")
    except Exception as e:
        print(f"Error parsing output: {e}")
        return 1e6

    loss = loss_fc(data)
    
    # Track the best parameters seen so far
    if loss < best_loss:
        best_loss = loss
        best_params = (deg_values.copy(), sigma_values.copy())
        print(f"New best found: deg={deg_values}, sigma={sigma_values}, loss={loss:.6f}")
    else:
        print(f"Evaluated: deg={deg_values}, sigma={sigma_values}, loss={loss:.6f}")
        
    return loss


if __name__ == "__main__":
    config_path = r"../../isis/register/default_config"
    n = 3 

    # Bounds: First 'n' elements are degrees, next 'n' are sigmas
    bounds = [(0, 3), (1, 4), (2, 5)] + [(0.5, 10)] * n

    try:
        print("Starting optimization. Press Ctrl+C to safely interrupt and retrieve best parameters.")
        result = dual_annealing(
            pipeline_loss,
            bounds=bounds,
            args=(config_path, n),
            maxiter=40,
            maxfun=300,
            no_local_search=True
        )

    except KeyboardInterrupt:
        print("\nKeyboard interrupt detected. Halting optimization.")

        if best_params is not None:
            deg_best, sigma_best = best_params
            print("\n--- Partial Optimization Results ---")
            print(f"deg_gauss   = {deg_best}")
            print(f"sigma_gauss = {sigma_best}")
            print(f"Best Loss   = {best_loss:.6f}")
            print("------------------------------------")
        else:
            print("No valid evaluation completed yet.")

        raise SystemExit(0)

    print("\n--- Optimization Complete ---")
    deg_best = np.round(result.x[:n]).astype(int)
    sigma_best = np.clip(result.x[n:], 0.5, 10.0)
    print(f"deg_gauss   = {deg_best}")
    print(f"sigma_gauss = {sigma_best}")
    print(f"Minimum Loss = {result.fun:.6f}")
    print("-----------------------------")